resolver 127.0.0.11 valid=10s ipv6=off;

server {
  listen 8000;
  client_max_body_size 10m;

  location /auth/v1/ {
    set $upstream http://auth:9999;
    rewrite ^/auth/v1/(.*)$ /$1 break;
    proxy_pass $upstream;
    proxy_set_header Host $host;
  }

  location /rest/v1/ {
    set $upstream http://rest:3000;
    rewrite ^/rest/v1/(.*)$ /$1 break;
    proxy_pass $upstream;
    proxy_set_header Host $host;
  }

  location /storage/v1/ {
    set $upstream http://storage:5000;
    rewrite ^/storage/v1/(.*)$ /$1 break;
    proxy_pass $upstream;
    proxy_set_header Host $host;
  }
}
